services:
  - type: web
    name: bhartiyam-frontend
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    pullRequestPreviewsEnabled: false

    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
