services:
  - type: web
    name: bhartiyam-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /.*       # This handles refresh in SPA like React
        destination: /index.html
